// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCshMzSDV_bmX9lIYlFI3fl3845Zre9M7Q',
    appId: '1:150852619880:web:c92cac452918ae649d75dd',
    messagingSenderId: '150852619880',
    projectId: 'evently-b3659',
    authDomain: 'evently-b3659.firebaseapp.com',
    storageBucket: 'evently-b3659.firebasestorage.app',
    measurementId: 'G-4H3WHM2TW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9hMob55qrqFc8S3GBdujtkutQjpoMxUQ',
    appId: '1:150852619880:android:c2c84d2ca28bee9b9d75dd',
    messagingSenderId: '150852619880',
    projectId: 'evently-b3659',
    storageBucket: 'evently-b3659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMfpbmbTGqa1zqiAH1j5BKbcF9L5Kge2E',
    appId: '1:150852619880:ios:7fb4d3db851ef6e09d75dd',
    messagingSenderId: '150852619880',
    projectId: 'evently-b3659',
    storageBucket: 'evently-b3659.firebasestorage.app',
    iosClientId: '150852619880-r4unfug5igf62gt2noq619fca0q7e897.apps.googleusercontent.com',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMfpbmbTGqa1zqiAH1j5BKbcF9L5Kge2E',
    appId: '1:150852619880:ios:7fb4d3db851ef6e09d75dd',
    messagingSenderId: '150852619880',
    projectId: 'evently-b3659',
    storageBucket: 'evently-b3659.firebasestorage.app',
    iosClientId: '150852619880-r4unfug5igf62gt2noq619fca0q7e897.apps.googleusercontent.com',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCshMzSDV_bmX9lIYlFI3fl3845Zre9M7Q',
    appId: '1:150852619880:web:33f5a4b9a9de3d429d75dd',
    messagingSenderId: '150852619880',
    projectId: 'evently-b3659',
    authDomain: 'evently-b3659.firebaseapp.com',
    storageBucket: 'evently-b3659.firebasestorage.app',
    measurementId: 'G-0H63R435LJ',
  );

}